// <auto-generated />
namespace HrManagementAlpha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLeave : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLeave));
        
        string IMigrationMetadata.Id
        {
            get { return "201606120739566_AddLeave"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
